In [28]:
import pandas as pd
import numpy as np
import matplotlib as mp
import glob

In [36]:
names = glob.glob('*.csv')

In [37]:
combine = pd.DataFrame()
for file in names:
    data = pd.read_csv(file, sep=';', encoding='windows-1251')
    combine = pd.concat([combine,data])

In [39]:
combine.shape

(8700, 14)

In [40]:
combine.describe()

,SKU,Остаток,Отзывов,Минимальная цена,Максимальная цена,Средняя цена,Продаж,Выручка,Рейтинг
count,8.700000e+03,8700.000000,8700.000000,8700.000000,8700.000000,8700.000000,8700.000000,8.700000e+03,8700.000000
mean,3.357336e+08,428.871954,163.976782,4150.068506,4150.068506,3967.837011,125.754253,1.980453e+05,3.638592
std,1.435977e+08,10827.104730,624.914378,6196.550483,6196.550483,5876.547885,281.901676,6.435439e+05,2.073244
min,2.981537e+07,0.000000,0.000000,100.000000,100.000000,100.000000,1.000000,1.669200e+04,0.000000
25%,2.027015e+08,10.000000,1.000000,662.000000,662.000000,625.000000,12.000000,2.756550e+04,3.430000
50%,3.025469e+08,40.000000,9.000000,1867.500000,1867.500000,1778.000000,36.000000,4.997800e+04,4.820000
75%,4.701780e+08,158.000000,71.000000,5722.000000,5722.000000,5530.250000,123.000000,1.271900e+05,4.960000
max,7.532814e+08,999979.000000,12739.000000,192735.000000,192735.000000,189886.000000,4600.000000,1.490118e+07,5.000000

In [62]:
combine.rename(columns = {'Название':'name','Категория':'category','Бренд':'brend','Остаток':'remainder', 'Отзывов':'Reviews', 'Минимальная цена':' min_price'
                          , 'Максимальная цена':'max_price', 'Средняя цена':'mean_price', 'Продаж':'sales'
                          , 'Выручка':' Revenue', 'Рейтинг':'Rating'}, inplace = True )

In [52]:
combine.head()

,SKU,name,category,brend,remainder,Reviews,min_price,max_price,mean_price,sales,Revenue,Ссылка на товар,Фото,Rating
0,144371875,Моторное масло IDEMITSU ZEPRO EURO SPEC 5W-40 ...,Автотовары,IDEMITSU,997,1228,1600,1600,1335,235,313661,https://www.ozon.ru/context/detail/id/144371875/,https://cdn1.ozone.ru/multimedia/1022220335.jpg,4.93
1,149354316,Шины зимние Yokohama Ice Guard IG50+ 185/65 R...,Автотовары,Yokohama,365,2,5280,5280,5280,61,322080,https://www.ozon.ru/context/detail/id/149354316/,https://cdn1.ozone.ru/multimedia/1019034419.jpg,5.00
2,149683967,Шины зимние Viatti Brina V-521 195/55 R15 85T...,Автотовары,Viatti,207,25,4764,4764,4762,65,309415,https://www.ozon.ru/context/detail/id/149683967/,https://cdn1.ozone.ru/multimedia/1020165280.jpg,4.84
3,149684966,Шины зимние Nokian Tyres RS2 215/55 R16 97R Н...,Автотовары,Nokian Tyres,502,1,7440,7440,7440,44,327360,https://www.ozon.ru/context/detail/id/149684966/,https://cdn1.ozone.ru/multimedia/1020165303.jpg,5.00
4,149697721,Шины летние Sailun KU39 Ecsta 225/55 R16 99V,Автотовары,Sailun,86,4,6202,6202,5925,55,328314,https://www.ozon.ru/context/detail/id/149697721/,https://cdn1.ozone.ru/s3/multimedia-q/62783068...,5.00

In [65]:
combine.sort_values(by='mean_price', ascending=False)

KeyError: 'mean_price'

In [66]:
combine.to_csv (r'my_data.csv', index= False )